#############################################################################
# Makefile for building: libsstLibreCAD2Lib_d.a
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  sstLibreCAD2Lib.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile sstLibreCAD2Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_QML_DEBUG
CFLAGS        = -pipe -g -fPIC -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -std=gnu++11 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I. -I../boost_1_68_0 -I../muparser-2.2.5/include -IHeader -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = sstLibreCAD2Lib_d1.0.0
DISTDIR = /home/uli/Entwicklung/sstLibreCAD2Lib/.tmp/sstLibreCAD2Lib_d1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/engine/rs_vector.cpp \
		lib/engine/rs.cpp \
		lib/engine/lc_rect.cpp \
		lib/engine/rs_color.cpp \
		lib/engine/rs_flags.cpp \
		lib/debug/rs_debug.cpp \
		lib/math/rs_math.cpp 
OBJECTS       = rs_vector.o \
		rs.o \
		lc_rect.o \
		rs_color.o \
		rs_flags.o \
		rs_debug.o \
		rs_math.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstLibreCAD2Lib.pro Header/rs.h \
		Header/rs_debug.h \
		Header/rs_math.h \
		Header/rs_vector.h \
		Header/rs_color.h \
		Header/rs_flags.h lib/engine/rs_vector.cpp \
		lib/engine/rs.cpp \
		lib/engine/lc_rect.cpp \
		lib/engine/rs_color.cpp \
		lib/engine/rs_flags.cpp \
		lib/debug/rs_debug.cpp \
		lib/math/rs_math.cpp
QMAKE_TARGET  = sstLibreCAD2Lib_d
DESTDIR       = ../libs/
TARGET        = libsstLibreCAD2Lib_d.a


first: all
####### Build rules

staticlib: ../libs/$(TARGET)

../libs/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@test -d ../libs/ || mkdir -p ../libs/
	-$(DEL_FILE) ../libs/$(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: sstLibreCAD2Lib.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		sstLibreCAD2Lib.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile sstLibreCAD2Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/clang.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
sstLibreCAD2Lib.pro:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile sstLibreCAD2Lib.pro -spec linux-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile ../libs/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Header/rs.h Header/rs_debug.h Header/rs_math.h Header/rs_vector.h Header/rs_color.h Header/rs_flags.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/engine/rs_vector.cpp lib/engine/rs.cpp lib/engine/lc_rect.cpp lib/engine/rs_color.cpp lib/engine/rs_flags.cpp lib/debug/rs_debug.cpp lib/math/rs_math.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) ../libs/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	clang++ -pipe -g -fPIC -std=gnu++11 -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

rs_vector.o: lib/engine/rs_vector.cpp Header/rs_vector.h \
		Header/rs.h \
		Header/rs_debug.h \
		Header/rs_math.h \
		Header/lc_rect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs_vector.o lib/engine/rs_vector.cpp

rs.o: lib/engine/rs.cpp Header/rs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs.o lib/engine/rs.cpp

lc_rect.o: lib/engine/lc_rect.cpp Header/lc_rect.h \
		Header/rs_vector.h \
		Header/rs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lc_rect.o lib/engine/lc_rect.cpp

rs_color.o: lib/engine/rs_color.cpp Header/rs_color.h \
		Header/rs.h \
		Header/rs_flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs_color.o lib/engine/rs_color.cpp

rs_flags.o: lib/engine/rs_flags.cpp Header/rs_flags.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs_flags.o lib/engine/rs_flags.cpp

rs_debug.o: lib/debug/rs_debug.cpp Header/rs_debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs_debug.o lib/debug/rs_debug.cpp

rs_math.o: lib/math/rs_math.cpp ../boost_1_68_0/boost/numeric/ublas/matrix.hpp \
		../boost_1_68_0/boost/config.hpp \
		../boost_1_68_0/boost/config/user.hpp \
		../boost_1_68_0/boost/config/detail/select_compiler_config.hpp \
		../boost_1_68_0/boost/config/compiler/nvcc.hpp \
		../boost_1_68_0/boost/config/compiler/gcc_xml.hpp \
		../boost_1_68_0/boost/config/compiler/cray.hpp \
		../boost_1_68_0/boost/config/compiler/common_edg.hpp \
		../boost_1_68_0/boost/config/compiler/comeau.hpp \
		../boost_1_68_0/boost/config/compiler/pathscale.hpp \
		../boost_1_68_0/boost/config/compiler/clang.hpp \
		../boost_1_68_0/boost/config/compiler/intel.hpp \
		../boost_1_68_0/boost/config/compiler/visualc.hpp \
		../boost_1_68_0/boost/config/pragma_message.hpp \
		../boost_1_68_0/boost/config/helper_macros.hpp \
		../boost_1_68_0/boost/config/compiler/gcc.hpp \
		../boost_1_68_0/boost/config/compiler/digitalmars.hpp \
		../boost_1_68_0/boost/config/compiler/kai.hpp \
		../boost_1_68_0/boost/config/compiler/sgi_mipspro.hpp \
		../boost_1_68_0/boost/config/compiler/compaq_cxx.hpp \
		../boost_1_68_0/boost/config/compiler/greenhills.hpp \
		../boost_1_68_0/boost/config/compiler/codegear.hpp \
		../boost_1_68_0/boost/config/compiler/borland.hpp \
		../boost_1_68_0/boost/config/compiler/metrowerks.hpp \
		../boost_1_68_0/boost/config/compiler/sunpro_cc.hpp \
		../boost_1_68_0/boost/config/compiler/hp_acc.hpp \
		../boost_1_68_0/boost/config/compiler/mpw.hpp \
		../boost_1_68_0/boost/config/compiler/xlcpp_zos.hpp \
		../boost_1_68_0/boost/config/compiler/xlcpp.hpp \
		../boost_1_68_0/boost/config/compiler/vacpp.hpp \
		../boost_1_68_0/boost/config/compiler/pgi.hpp \
		../boost_1_68_0/boost/config/detail/select_stdlib_config.hpp \
		../boost_1_68_0/boost/config/stdlib/stlport.hpp \
		../boost_1_68_0/boost/config/stdlib/libcomo.hpp \
		../boost_1_68_0/boost/config/no_tr1/utility.hpp \
		../boost_1_68_0/boost/config/stdlib/roguewave.hpp \
		../boost_1_68_0/boost/config/stdlib/libcpp.hpp \
		../boost_1_68_0/boost/config/stdlib/libstdcpp3.hpp \
		../boost_1_68_0/boost/config/stdlib/sgi.hpp \
		../boost_1_68_0/boost/config/stdlib/msl.hpp \
		../boost_1_68_0/boost/config/detail/posix_features.hpp \
		../boost_1_68_0/boost/config/stdlib/xlcpp_zos.hpp \
		../boost_1_68_0/boost/config/stdlib/vacpp.hpp \
		../boost_1_68_0/boost/config/stdlib/modena.hpp \
		../boost_1_68_0/boost/config/stdlib/dinkumware.hpp \
		../boost_1_68_0/boost/config/detail/select_platform_config.hpp \
		../boost_1_68_0/boost/config/platform/linux.hpp \
		../boost_1_68_0/boost/config/platform/bsd.hpp \
		../boost_1_68_0/boost/config/platform/solaris.hpp \
		../boost_1_68_0/boost/config/platform/irix.hpp \
		../boost_1_68_0/boost/config/platform/hpux.hpp \
		../boost_1_68_0/boost/config/platform/cygwin.hpp \
		../boost_1_68_0/boost/config/platform/win32.hpp \
		../boost_1_68_0/boost/config/platform/beos.hpp \
		../boost_1_68_0/boost/config/platform/macos.hpp \
		../boost_1_68_0/boost/config/platform/zos.hpp \
		../boost_1_68_0/boost/config/platform/aix.hpp \
		../boost_1_68_0/boost/config/platform/amigaos.hpp \
		../boost_1_68_0/boost/config/platform/qnxnto.hpp \
		../boost_1_68_0/boost/config/platform/vxworks.hpp \
		../boost_1_68_0/boost/config/platform/symbian.hpp \
		../boost_1_68_0/boost/config/platform/cray.hpp \
		../boost_1_68_0/boost/config/platform/vms.hpp \
		../boost_1_68_0/boost/config/detail/suffix.hpp \
		../boost_1_68_0/boost/numeric/ublas/vector.hpp \
		../boost_1_68_0/boost/numeric/ublas/storage.hpp \
		../boost_1_68_0/boost/shared_array.hpp \
		../boost_1_68_0/boost/smart_ptr/shared_array.hpp \
		../boost_1_68_0/boost/assert.hpp \
		../boost_1_68_0/boost/current_function.hpp \
		../boost_1_68_0/boost/checked_delete.hpp \
		../boost_1_68_0/boost/core/checked_delete.hpp \
		../boost_1_68_0/boost/smart_ptr/shared_ptr.hpp \
		../boost_1_68_0/boost/config/no_tr1/memory.hpp \
		../boost_1_68_0/boost/throw_exception.hpp \
		../boost_1_68_0/boost/detail/workaround.hpp \
		../boost_1_68_0/boost/config/workaround.hpp \
		../boost_1_68_0/boost/exception/exception.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/shared_count.hpp \
		../boost_1_68_0/boost/smart_ptr/bad_weak_ptr.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_has_sync.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_nt.hpp \
		../boost_1_68_0/boost/detail/sp_typeinfo.hpp \
		../boost_1_68_0/boost/core/typeinfo.hpp \
		../boost_1_68_0/boost/core/demangle.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_spin.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_pool.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_std_atomic.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/yield_k.hpp \
		../boost_1_68_0/boost/predef.h \
		../boost_1_68_0/boost/predef/language.h \
		../boost_1_68_0/boost/predef/language/stdc.h \
		../boost_1_68_0/boost/predef/version_number.h \
		../boost_1_68_0/boost/predef/make.h \
		../boost_1_68_0/boost/predef/detail/test.h \
		../boost_1_68_0/boost/predef/language/stdcpp.h \
		../boost_1_68_0/boost/predef/language/objc.h \
		../boost_1_68_0/boost/predef/language/cuda.h \
		../boost_1_68_0/boost/predef/architecture.h \
		../boost_1_68_0/boost/predef/architecture/alpha.h \
		../boost_1_68_0/boost/predef/architecture/arm.h \
		../boost_1_68_0/boost/predef/architecture/blackfin.h \
		../boost_1_68_0/boost/predef/architecture/convex.h \
		../boost_1_68_0/boost/predef/architecture/ia64.h \
		../boost_1_68_0/boost/predef/architecture/m68k.h \
		../boost_1_68_0/boost/predef/architecture/mips.h \
		../boost_1_68_0/boost/predef/architecture/parisc.h \
		../boost_1_68_0/boost/predef/architecture/ppc.h \
		../boost_1_68_0/boost/predef/architecture/ptx.h \
		../boost_1_68_0/boost/predef/architecture/pyramid.h \
		../boost_1_68_0/boost/predef/architecture/rs6k.h \
		../boost_1_68_0/boost/predef/architecture/sparc.h \
		../boost_1_68_0/boost/predef/architecture/superh.h \
		../boost_1_68_0/boost/predef/architecture/sys370.h \
		../boost_1_68_0/boost/predef/architecture/sys390.h \
		../boost_1_68_0/boost/predef/architecture/x86.h \
		../boost_1_68_0/boost/predef/architecture/x86/32.h \
		../boost_1_68_0/boost/predef/architecture/x86/64.h \
		../boost_1_68_0/boost/predef/architecture/z.h \
		../boost_1_68_0/boost/predef/compiler.h \
		../boost_1_68_0/boost/predef/compiler/borland.h \
		../boost_1_68_0/boost/predef/detail/comp_detected.h \
		../boost_1_68_0/boost/predef/compiler/clang.h \
		../boost_1_68_0/boost/predef/compiler/comeau.h \
		../boost_1_68_0/boost/predef/compiler/compaq.h \
		../boost_1_68_0/boost/predef/compiler/diab.h \
		../boost_1_68_0/boost/predef/compiler/digitalmars.h \
		../boost_1_68_0/boost/predef/compiler/dignus.h \
		../boost_1_68_0/boost/predef/compiler/edg.h \
		../boost_1_68_0/boost/predef/compiler/ekopath.h \
		../boost_1_68_0/boost/predef/compiler/gcc_xml.h \
		../boost_1_68_0/boost/predef/compiler/gcc.h \
		../boost_1_68_0/boost/predef/compiler/greenhills.h \
		../boost_1_68_0/boost/predef/compiler/hp_acc.h \
		../boost_1_68_0/boost/predef/compiler/iar.h \
		../boost_1_68_0/boost/predef/compiler/ibm.h \
		../boost_1_68_0/boost/predef/compiler/intel.h \
		../boost_1_68_0/boost/predef/compiler/kai.h \
		../boost_1_68_0/boost/predef/compiler/llvm.h \
		../boost_1_68_0/boost/predef/compiler/metaware.h \
		../boost_1_68_0/boost/predef/compiler/metrowerks.h \
		../boost_1_68_0/boost/predef/compiler/microtec.h \
		../boost_1_68_0/boost/predef/compiler/mpw.h \
		../boost_1_68_0/boost/predef/compiler/nvcc.h \
		../boost_1_68_0/boost/predef/compiler/palm.h \
		../boost_1_68_0/boost/predef/compiler/pgi.h \
		../boost_1_68_0/boost/predef/compiler/sgi_mipspro.h \
		../boost_1_68_0/boost/predef/compiler/sunpro.h \
		../boost_1_68_0/boost/predef/compiler/tendra.h \
		../boost_1_68_0/boost/predef/compiler/visualc.h \
		../boost_1_68_0/boost/predef/compiler/watcom.h \
		../boost_1_68_0/boost/predef/library.h \
		../boost_1_68_0/boost/predef/library/c.h \
		../boost_1_68_0/boost/predef/library/c/_prefix.h \
		../boost_1_68_0/boost/predef/detail/_cassert.h \
		../boost_1_68_0/boost/predef/library/c/cloudabi.h \
		../boost_1_68_0/boost/predef/library/c/gnu.h \
		../boost_1_68_0/boost/predef/library/c/uc.h \
		../boost_1_68_0/boost/predef/library/c/vms.h \
		../boost_1_68_0/boost/predef/library/c/zos.h \
		../boost_1_68_0/boost/predef/library/std.h \
		../boost_1_68_0/boost/predef/library/std/_prefix.h \
		../boost_1_68_0/boost/predef/detail/_exception.h \
		../boost_1_68_0/boost/predef/library/std/cxx.h \
		../boost_1_68_0/boost/predef/library/std/dinkumware.h \
		../boost_1_68_0/boost/predef/library/std/libcomo.h \
		../boost_1_68_0/boost/predef/library/std/modena.h \
		../boost_1_68_0/boost/predef/library/std/msl.h \
		../boost_1_68_0/boost/predef/library/std/roguewave.h \
		../boost_1_68_0/boost/predef/library/std/sgi.h \
		../boost_1_68_0/boost/predef/library/std/stdcpp3.h \
		../boost_1_68_0/boost/predef/library/std/stlport.h \
		../boost_1_68_0/boost/predef/library/std/vacpp.h \
		../boost_1_68_0/boost/predef/os.h \
		../boost_1_68_0/boost/predef/os/aix.h \
		../boost_1_68_0/boost/predef/detail/os_detected.h \
		../boost_1_68_0/boost/predef/os/amigaos.h \
		../boost_1_68_0/boost/predef/os/android.h \
		../boost_1_68_0/boost/predef/os/beos.h \
		../boost_1_68_0/boost/predef/os/bsd.h \
		../boost_1_68_0/boost/predef/os/macos.h \
		../boost_1_68_0/boost/predef/os/ios.h \
		../boost_1_68_0/boost/predef/os/bsd/bsdi.h \
		../boost_1_68_0/boost/predef/os/bsd/dragonfly.h \
		../boost_1_68_0/boost/predef/os/bsd/free.h \
		../boost_1_68_0/boost/predef/os/bsd/open.h \
		../boost_1_68_0/boost/predef/os/bsd/net.h \
		../boost_1_68_0/boost/predef/os/cygwin.h \
		../boost_1_68_0/boost/predef/os/haiku.h \
		../boost_1_68_0/boost/predef/os/hpux.h \
		../boost_1_68_0/boost/predef/os/irix.h \
		../boost_1_68_0/boost/predef/os/linux.h \
		../boost_1_68_0/boost/predef/os/os400.h \
		../boost_1_68_0/boost/predef/os/qnxnto.h \
		../boost_1_68_0/boost/predef/os/solaris.h \
		../boost_1_68_0/boost/predef/os/unix.h \
		../boost_1_68_0/boost/predef/os/vms.h \
		../boost_1_68_0/boost/predef/os/windows.h \
		../boost_1_68_0/boost/predef/other.h \
		../boost_1_68_0/boost/predef/other/endian.h \
		../boost_1_68_0/boost/predef/platform.h \
		../boost_1_68_0/boost/predef/platform/cloudabi.h \
		../boost_1_68_0/boost/predef/detail/platform_detected.h \
		../boost_1_68_0/boost/predef/platform/mingw.h \
		../boost_1_68_0/boost/predef/platform/mingw32.h \
		../boost_1_68_0/boost/predef/platform/mingw64.h \
		../boost_1_68_0/boost/predef/platform/windows_uwp.h \
		../boost_1_68_0/boost/predef/platform/windows_desktop.h \
		../boost_1_68_0/boost/predef/platform/windows_phone.h \
		../boost_1_68_0/boost/predef/platform/windows_server.h \
		../boost_1_68_0/boost/predef/platform/windows_store.h \
		../boost_1_68_0/boost/predef/platform/windows_system.h \
		../boost_1_68_0/boost/predef/platform/windows_runtime.h \
		../boost_1_68_0/boost/predef/platform/ios.h \
		../boost_1_68_0/boost/predef/hardware.h \
		../boost_1_68_0/boost/predef/hardware/simd.h \
		../boost_1_68_0/boost/predef/hardware/simd/x86.h \
		../boost_1_68_0/boost/predef/hardware/simd/x86/versions.h \
		../boost_1_68_0/boost/predef/hardware/simd/x86_amd.h \
		../boost_1_68_0/boost/predef/hardware/simd/x86_amd/versions.h \
		../boost_1_68_0/boost/predef/hardware/simd/arm.h \
		../boost_1_68_0/boost/predef/hardware/simd/arm/versions.h \
		../boost_1_68_0/boost/predef/hardware/simd/ppc.h \
		../boost_1_68_0/boost/predef/hardware/simd/ppc/versions.h \
		../boost_1_68_0/boost/predef/version.h \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_sync.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_pt.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_gcc_arm.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_w32.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_interlocked.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/spinlock_nt.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_pt.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_clang.hpp \
		../boost_1_68_0/boost/cstdint.hpp \
		../boost_1_68_0/boost/limits.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_snc_ps3.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_acc_ia64.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_gcc_ia64.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_vacpp_ppc.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_cw_ppc.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_gcc_ppc.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_gcc_mips.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_sync.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_gcc_sparc.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_w32.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_base_aix.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_counted_impl.hpp \
		../boost_1_68_0/boost/core/addressof.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/quick_allocator.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/lightweight_mutex.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/lwm_nop.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/lwm_pthreads.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/lwm_win32_cs.hpp \
		../boost_1_68_0/boost/type_traits/type_with_alignment.hpp \
		../boost_1_68_0/boost/type_traits/alignment_of.hpp \
		../boost_1_68_0/boost/type_traits/intrinsics.hpp \
		../boost_1_68_0/boost/type_traits/detail/config.hpp \
		../boost_1_68_0/boost/version.hpp \
		../boost_1_68_0/boost/type_traits/is_same.hpp \
		../boost_1_68_0/boost/type_traits/integral_constant.hpp \
		../boost_1_68_0/boost/type_traits/is_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_lvalue_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_rvalue_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_volatile.hpp \
		../boost_1_68_0/boost/type_traits/is_void.hpp \
		../boost_1_68_0/boost/type_traits/is_pod.hpp \
		../boost_1_68_0/boost/type_traits/is_scalar.hpp \
		../boost_1_68_0/boost/type_traits/is_arithmetic.hpp \
		../boost_1_68_0/boost/type_traits/is_integral.hpp \
		../boost_1_68_0/boost/type_traits/is_floating_point.hpp \
		../boost_1_68_0/boost/type_traits/is_enum.hpp \
		../boost_1_68_0/boost/type_traits/add_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_convertible.hpp \
		../boost_1_68_0/boost/type_traits/is_complete.hpp \
		../boost_1_68_0/boost/type_traits/declval.hpp \
		../boost_1_68_0/boost/type_traits/add_rvalue_reference.hpp \
		../boost_1_68_0/boost/type_traits/remove_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_function.hpp \
		../boost_1_68_0/boost/type_traits/detail/is_function_ptr_helper.hpp \
		../boost_1_68_0/boost/type_traits/detail/is_function_ptr_tester.hpp \
		../boost_1_68_0/boost/type_traits/detail/yes_no_type.hpp \
		../boost_1_68_0/boost/type_traits/is_array.hpp \
		../boost_1_68_0/boost/static_assert.hpp \
		../boost_1_68_0/boost/type_traits/is_abstract.hpp \
		../boost_1_68_0/boost/type_traits/is_class.hpp \
		../boost_1_68_0/boost/type_traits/is_union.hpp \
		../boost_1_68_0/boost/type_traits/is_polymorphic.hpp \
		../boost_1_68_0/boost/type_traits/add_lvalue_reference.hpp \
		../boost_1_68_0/boost/type_traits/is_pointer.hpp \
		../boost_1_68_0/boost/type_traits/is_member_pointer.hpp \
		../boost_1_68_0/boost/type_traits/is_member_function_pointer.hpp \
		../boost_1_68_0/boost/type_traits/detail/is_mem_fun_pointer_impl.hpp \
		../boost_1_68_0/boost/type_traits/remove_cv.hpp \
		../boost_1_68_0/boost/type_traits/detail/is_mem_fun_pointer_tester.hpp \
		../boost_1_68_0/boost/type_traits/conditional.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_disable_deprecated.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_convertible.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_nullptr_t.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/sp_noexcept.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/operator_bool.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/local_sp_deleter.hpp \
		../boost_1_68_0/boost/smart_ptr/detail/local_counted_base.hpp \
		../boost_1_68_0/boost/serialization/array.hpp \
		../boost_1_68_0/boost/serialization/array_wrapper.hpp \
		../boost_1_68_0/boost/serialization/nvp.hpp \
		../boost_1_68_0/boost/serialization/level.hpp \
		../boost_1_68_0/boost/type_traits/is_fundamental.hpp \
		../boost_1_68_0/boost/type_traits/is_base_and_derived.hpp \
		../boost_1_68_0/boost/mpl/eval_if.hpp \
		../boost_1_68_0/boost/mpl/if.hpp \
		../boost_1_68_0/boost/mpl/aux_/value_wknd.hpp \
		../boost_1_68_0/boost/mpl/aux_/static_cast.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/workaround.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/integral.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/msvc.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/eti.hpp \
		../boost_1_68_0/boost/mpl/int.hpp \
		../boost_1_68_0/boost/mpl/int_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/adl_barrier.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/adl.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/intel.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/gcc.hpp \
		../boost_1_68_0/boost/mpl/aux_/nttp_decl.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/nttp.hpp \
		../boost_1_68_0/boost/preprocessor/cat.hpp \
		../boost_1_68_0/boost/preprocessor/config/config.hpp \
		../boost_1_68_0/boost/mpl/aux_/integral_wrapper.hpp \
		../boost_1_68_0/boost/mpl/integral_c_tag.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/static_constant.hpp \
		../boost_1_68_0/boost/mpl/aux_/na_spec.hpp \
		../boost_1_68_0/boost/mpl/lambda_fwd.hpp \
		../boost_1_68_0/boost/mpl/void_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/na.hpp \
		../boost_1_68_0/boost/mpl/bool.hpp \
		../boost_1_68_0/boost/mpl/bool_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/na_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/ctps.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/lambda.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/ttp.hpp \
		../boost_1_68_0/boost/mpl/aux_/lambda_arity_param.hpp \
		../boost_1_68_0/boost/mpl/aux_/template_arity_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/arity.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/dtp.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/params.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/preprocessor.hpp \
		../boost_1_68_0/boost/preprocessor/comma_if.hpp \
		../boost_1_68_0/boost/preprocessor/punctuation/comma_if.hpp \
		../boost_1_68_0/boost/preprocessor/control/if.hpp \
		../boost_1_68_0/boost/preprocessor/control/iif.hpp \
		../boost_1_68_0/boost/preprocessor/logical/bool.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/empty.hpp \
		../boost_1_68_0/boost/preprocessor/punctuation/comma.hpp \
		../boost_1_68_0/boost/preprocessor/repeat.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/repeat.hpp \
		../boost_1_68_0/boost/preprocessor/debug/error.hpp \
		../boost_1_68_0/boost/preprocessor/detail/auto_rec.hpp \
		../boost_1_68_0/boost/preprocessor/detail/dmc/auto_rec.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/eat.hpp \
		../boost_1_68_0/boost/preprocessor/inc.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/inc.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/enum.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/def_params_tail.hpp \
		../boost_1_68_0/boost/mpl/limits/arity.hpp \
		../boost_1_68_0/boost/preprocessor/logical/and.hpp \
		../boost_1_68_0/boost/preprocessor/logical/bitand.hpp \
		../boost_1_68_0/boost/preprocessor/identity.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/identity.hpp \
		../boost_1_68_0/boost/preprocessor/empty.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/filter_params.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/sub.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/tuple.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/sub.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/dec.hpp \
		../boost_1_68_0/boost/preprocessor/control/while.hpp \
		../boost_1_68_0/boost/preprocessor/list/fold_left.hpp \
		../boost_1_68_0/boost/preprocessor/list/detail/edg/fold_left.hpp \
		../boost_1_68_0/boost/preprocessor/control/expr_iif.hpp \
		../boost_1_68_0/boost/preprocessor/list/adt.hpp \
		../boost_1_68_0/boost/preprocessor/detail/is_binary.hpp \
		../boost_1_68_0/boost/preprocessor/detail/check.hpp \
		../boost_1_68_0/boost/preprocessor/logical/compl.hpp \
		../boost_1_68_0/boost/preprocessor/list/detail/dmc/fold_left.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/elem.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/expand.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/overload.hpp \
		../boost_1_68_0/boost/preprocessor/variadic/size.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/rem.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/detail/is_single_return.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/is_1.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/is_empty.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/is_empty_variadic.hpp \
		../boost_1_68_0/boost/preprocessor/punctuation/is_begin_parens.hpp \
		../boost_1_68_0/boost/preprocessor/punctuation/detail/is_begin_parens.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/detail/is_empty.hpp \
		../boost_1_68_0/boost/preprocessor/detail/split.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/size.hpp \
		../boost_1_68_0/boost/preprocessor/variadic/elem.hpp \
		../boost_1_68_0/boost/preprocessor/list/detail/fold_left.hpp \
		../boost_1_68_0/boost/preprocessor/list/fold_right.hpp \
		../boost_1_68_0/boost/preprocessor/list/detail/edg/fold_right.hpp \
		../boost_1_68_0/boost/preprocessor/list/detail/fold_right.hpp \
		../boost_1_68_0/boost/preprocessor/list/reverse.hpp \
		../boost_1_68_0/boost/preprocessor/control/detail/edg/while.hpp \
		../boost_1_68_0/boost/preprocessor/control/detail/msvc/while.hpp \
		../boost_1_68_0/boost/preprocessor/control/detail/dmc/while.hpp \
		../boost_1_68_0/boost/preprocessor/control/detail/while.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/add.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/overload_resolution.hpp \
		../boost_1_68_0/boost/mpl/aux_/lambda_support.hpp \
		../boost_1_68_0/boost/mpl/aux_/yes_no.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/arrays.hpp \
		../boost_1_68_0/boost/preprocessor/tuple/to_list.hpp \
		../boost_1_68_0/boost/preprocessor/list/for_each_i.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/for.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/detail/edg/for.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/detail/msvc/for.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/detail/dmc/for.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/detail/for.hpp \
		../boost_1_68_0/boost/mpl/integral_c.hpp \
		../boost_1_68_0/boost/mpl/integral_c_fwd.hpp \
		../boost_1_68_0/boost/serialization/level_enum.hpp \
		../boost_1_68_0/boost/serialization/tracking.hpp \
		../boost_1_68_0/boost/mpl/identity.hpp \
		../boost_1_68_0/boost/mpl/equal_to.hpp \
		../boost_1_68_0/boost/mpl/aux_/comparison_op.hpp \
		../boost_1_68_0/boost/mpl/aux_/numeric_op.hpp \
		../boost_1_68_0/boost/mpl/numeric_cast.hpp \
		../boost_1_68_0/boost/mpl/apply_wrap.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_apply.hpp \
		../boost_1_68_0/boost/mpl/has_xxx.hpp \
		../boost_1_68_0/boost/mpl/aux_/type_wrapper.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/has_xxx.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/msvc_typename.hpp \
		../boost_1_68_0/boost/preprocessor/array/elem.hpp \
		../boost_1_68_0/boost/preprocessor/array/data.hpp \
		../boost_1_68_0/boost/preprocessor/array/size.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_params.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_trailing_params.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/has_apply.hpp \
		../boost_1_68_0/boost/mpl/aux_/msvc_never_true.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/use_preprocessed.hpp \
		../boost_1_68_0/boost/mpl/aux_/include_preprocessed.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/compiler.hpp \
		../boost_1_68_0/boost/preprocessor/stringize.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/add.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/bcc.hpp \
		../boost_1_68_0/boost/preprocessor/iterate.hpp \
		../boost_1_68_0/boost/preprocessor/iteration/iterate.hpp \
		../boost_1_68_0/boost/preprocessor/slot/slot.hpp \
		../boost_1_68_0/boost/preprocessor/slot/detail/def.hpp \
		../boost_1_68_0/boost/mpl/aux_/msvc_dtw.hpp \
		../boost_1_68_0/boost/mpl/tag.hpp \
		../boost_1_68_0/boost/mpl/void.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_tag.hpp \
		../boost_1_68_0/boost/mpl/aux_/numeric_cast_utils.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/forwarding.hpp \
		../boost_1_68_0/boost/mpl/aux_/msvc_eti_base.hpp \
		../boost_1_68_0/boost/mpl/aux_/is_msvc_eti_arg.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/partial_spec_params.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/repeat.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/ext_params.hpp \
		../boost_1_68_0/boost/preprocessor/dec.hpp \
		../boost_1_68_0/boost/mpl/greater.hpp \
		../boost_1_68_0/boost/serialization/tracking_enum.hpp \
		../boost_1_68_0/boost/serialization/type_info_implementation.hpp \
		../boost_1_68_0/boost/serialization/traits.hpp \
		../boost_1_68_0/boost/serialization/split_member.hpp \
		../boost_1_68_0/boost/serialization/access.hpp \
		../boost_1_68_0/boost/serialization/base_object.hpp \
		../boost_1_68_0/boost/type_traits/is_const.hpp \
		../boost_1_68_0/boost/serialization/force_include.hpp \
		../boost_1_68_0/boost/serialization/void_cast_fwd.hpp \
		../boost_1_68_0/boost/serialization/wrapper.hpp \
		../boost_1_68_0/boost/serialization/collection_size_type.hpp \
		../boost_1_68_0/boost/serialization/strong_typedef.hpp \
		../boost_1_68_0/boost/operators.hpp \
		../boost_1_68_0/boost/operators_v1.hpp \
		../boost_1_68_0/boost/type_traits/has_nothrow_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_assign.hpp \
		../boost_1_68_0/boost/type_traits/is_assignable.hpp \
		../boost_1_68_0/boost/type_traits/has_nothrow_constructor.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_constructor.hpp \
		../boost_1_68_0/boost/type_traits/is_default_constructible.hpp \
		../boost_1_68_0/boost/type_traits/remove_all_extents.hpp \
		../boost_1_68_0/boost/type_traits/has_nothrow_copy.hpp \
		../boost_1_68_0/boost/type_traits/is_copy_constructible.hpp \
		../boost_1_68_0/boost/type_traits/is_constructible.hpp \
		../boost_1_68_0/boost/type_traits/is_destructible.hpp \
		../boost_1_68_0/boost/noncopyable.hpp \
		../boost_1_68_0/boost/core/noncopyable.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_copy.hpp \
		../boost_1_68_0/boost/type_traits/add_const.hpp \
		../boost_1_68_0/boost/serialization/split_free.hpp \
		../boost_1_68_0/boost/serialization/serialization.hpp \
		../boost_1_68_0/boost/serialization/is_bitwise_serializable.hpp \
		../boost_1_68_0/boost/serialization/array_optimization.hpp \
		../boost_1_68_0/boost/mpl/always.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/default_params.hpp \
		../boost_1_68_0/boost/mpl/aux_/arity_spec.hpp \
		../boost_1_68_0/boost/mpl/apply.hpp \
		../boost_1_68_0/boost/mpl/apply_fwd.hpp \
		../boost_1_68_0/boost/mpl/placeholders.hpp \
		../boost_1_68_0/boost/mpl/arg.hpp \
		../boost_1_68_0/boost/mpl/arg_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/na_assert.hpp \
		../boost_1_68_0/boost/mpl/assert.hpp \
		../boost_1_68_0/boost/mpl/not.hpp \
		../boost_1_68_0/boost/mpl/aux_/nested_type_wknd.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/gpu.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/pp_counter.hpp \
		../boost_1_68_0/boost/mpl/aux_/arg_typedef.hpp \
		../boost_1_68_0/boost/mpl/lambda.hpp \
		../boost_1_68_0/boost/mpl/bind.hpp \
		../boost_1_68_0/boost/mpl/bind_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/bind.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/dmc_ambiguous_ctps.hpp \
		../boost_1_68_0/boost/mpl/next.hpp \
		../boost_1_68_0/boost/mpl/next_prior.hpp \
		../boost_1_68_0/boost/mpl/aux_/common_name_wknd.hpp \
		../boost_1_68_0/boost/mpl/protect.hpp \
		../boost_1_68_0/boost/mpl/aux_/count_args.hpp \
		../boost_1_68_0/boost/preprocessor/expr_if.hpp \
		../boost_1_68_0/boost/preprocessor/control/expr_if.hpp \
		../boost_1_68_0/boost/preprocessor/enum_shifted_params.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_shifted_params.hpp \
		../boost_1_68_0/boost/mpl/aux_/full_lambda.hpp \
		../boost_1_68_0/boost/mpl/quote.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_type.hpp \
		../boost_1_68_0/boost/mpl/aux_/template_arity.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_rebind.hpp \
		../boost_1_68_0/boost/mpl/aux_/msvc_is_class.hpp \
		../boost_1_68_0/boost/mpl/aux_/preprocessor/range.hpp \
		../boost_1_68_0/boost/preprocessor/seq/subseq.hpp \
		../boost_1_68_0/boost/preprocessor/seq/first_n.hpp \
		../boost_1_68_0/boost/preprocessor/seq/detail/split.hpp \
		../boost_1_68_0/boost/preprocessor/seq/rest_n.hpp \
		../boost_1_68_0/boost/preprocessor/comparison/not_equal.hpp \
		../boost_1_68_0/boost/preprocessor/seq/detail/is_empty.hpp \
		../boost_1_68_0/boost/preprocessor/seq/size.hpp \
		../boost_1_68_0/boost/preprocessor/seq/fold_left.hpp \
		../boost_1_68_0/boost/preprocessor/seq/seq.hpp \
		../boost_1_68_0/boost/preprocessor/seq/elem.hpp \
		../boost_1_68_0/boost/mpl/aux_/lambda_no_ctps.hpp \
		../boost_1_68_0/boost/mpl/is_placeholder.hpp \
		../boost_1_68_0/boost/type_traits/remove_const.hpp \
		../boost_1_68_0/boost/numeric/ublas/exception.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/config.hpp \
		../boost_1_68_0/boost/mpl/and.hpp \
		../boost_1_68_0/boost/mpl/aux_/logical_op.hpp \
		../boost_1_68_0/boost/numeric/ublas/fwd.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/definitions.hpp \
		../boost_1_68_0/boost/numeric/ublas/traits.hpp \
		../boost_1_68_0/boost/config/no_tr1/cmath.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/iterator.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/returntype_deduction.hpp \
		../boost_1_68_0/boost/mpl/vector/vector20.hpp \
		../boost_1_68_0/boost/mpl/vector/vector10.hpp \
		../boost_1_68_0/boost/mpl/vector/vector0.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/at.hpp \
		../boost_1_68_0/boost/mpl/at_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/tag.hpp \
		../boost_1_68_0/boost/mpl/aux_/config/typeof.hpp \
		../boost_1_68_0/boost/mpl/long.hpp \
		../boost_1_68_0/boost/mpl/long_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/front.hpp \
		../boost_1_68_0/boost/mpl/front_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/push_front.hpp \
		../boost_1_68_0/boost/mpl/push_front_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/item.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/pop_front.hpp \
		../boost_1_68_0/boost/mpl/pop_front_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/push_back.hpp \
		../boost_1_68_0/boost/mpl/push_back_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/pop_back.hpp \
		../boost_1_68_0/boost/mpl/pop_back_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/back.hpp \
		../boost_1_68_0/boost/mpl/back_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/clear.hpp \
		../boost_1_68_0/boost/mpl/clear_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/vector0.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/iterator.hpp \
		../boost_1_68_0/boost/mpl/iterator_tags.hpp \
		../boost_1_68_0/boost/mpl/plus.hpp \
		../boost_1_68_0/boost/mpl/aux_/arithmetic_op.hpp \
		../boost_1_68_0/boost/mpl/aux_/largest_int.hpp \
		../boost_1_68_0/boost/mpl/minus.hpp \
		../boost_1_68_0/boost/mpl/advance_fwd.hpp \
		../boost_1_68_0/boost/mpl/distance_fwd.hpp \
		../boost_1_68_0/boost/mpl/prior.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/O1_size.hpp \
		../boost_1_68_0/boost/mpl/O1_size_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/size.hpp \
		../boost_1_68_0/boost/mpl/size_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/empty.hpp \
		../boost_1_68_0/boost/mpl/empty_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/begin_end.hpp \
		../boost_1_68_0/boost/mpl/begin_end_fwd.hpp \
		../boost_1_68_0/boost/mpl/vector/aux_/include_preprocessed.hpp \
		../boost_1_68_0/boost/mpl/at.hpp \
		../boost_1_68_0/boost/mpl/aux_/at_impl.hpp \
		../boost_1_68_0/boost/mpl/begin_end.hpp \
		../boost_1_68_0/boost/mpl/aux_/begin_end_impl.hpp \
		../boost_1_68_0/boost/mpl/sequence_tag_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_begin.hpp \
		../boost_1_68_0/boost/mpl/aux_/traits_lambda_spec.hpp \
		../boost_1_68_0/boost/mpl/sequence_tag.hpp \
		../boost_1_68_0/boost/mpl/advance.hpp \
		../boost_1_68_0/boost/mpl/less.hpp \
		../boost_1_68_0/boost/mpl/negate.hpp \
		../boost_1_68_0/boost/mpl/aux_/advance_forward.hpp \
		../boost_1_68_0/boost/mpl/limits/unrolling.hpp \
		../boost_1_68_0/boost/mpl/aux_/advance_backward.hpp \
		../boost_1_68_0/boost/mpl/deref.hpp \
		../boost_1_68_0/boost/mpl/aux_/msvc_type.hpp \
		../boost_1_68_0/boost/mpl/or.hpp \
		../boost_1_68_0/boost/utility/enable_if.hpp \
		../boost_1_68_0/boost/core/enable_if.hpp \
		../boost_1_68_0/boost/numeric/interval.hpp \
		../boost_1_68_0/boost/numeric/interval/interval.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/interval_prototype.hpp \
		../boost_1_68_0/boost/numeric/interval/policies.hpp \
		../boost_1_68_0/boost/numeric/interval/hw_rounding.hpp \
		../boost_1_68_0/boost/numeric/interval/rounding.hpp \
		../boost_1_68_0/boost/numeric/interval/rounded_arith.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/bugs.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/c99_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/c99sub_rounding_control.hpp \
		../boost_1_68_0/boost/detail/fenv.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/x86_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/x86gcc_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/bcc_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/msvc_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/ppc_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/sparc_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/alpha_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/ia64_rounding_control.hpp \
		../boost_1_68_0/boost/numeric/interval/rounded_transc.hpp \
		../boost_1_68_0/boost/numeric/interval/constants.hpp \
		../boost_1_68_0/boost/numeric/interval/checking.hpp \
		../boost_1_68_0/boost/numeric/interval/compare.hpp \
		../boost_1_68_0/boost/numeric/interval/compare/certain.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/test_input.hpp \
		../boost_1_68_0/boost/numeric/interval/compare/possible.hpp \
		../boost_1_68_0/boost/numeric/interval/compare/explicit.hpp \
		../boost_1_68_0/boost/numeric/interval/compare/lexicographic.hpp \
		../boost_1_68_0/boost/numeric/interval/compare/set.hpp \
		../boost_1_68_0/boost/numeric/interval/utility.hpp \
		../boost_1_68_0/boost/numeric/interval/arith.hpp \
		../boost_1_68_0/boost/numeric/interval/detail/division.hpp \
		../boost_1_68_0/boost/numeric/interval/arith2.hpp \
		../boost_1_68_0/boost/numeric/interval/arith3.hpp \
		../boost_1_68_0/boost/numeric/interval/transc.hpp \
		../boost_1_68_0/boost/type_traits.hpp \
		../boost_1_68_0/boost/type_traits/add_cv.hpp \
		../boost_1_68_0/boost/type_traits/add_pointer.hpp \
		../boost_1_68_0/boost/type_traits/add_volatile.hpp \
		../boost_1_68_0/boost/type_traits/aligned_storage.hpp \
		../boost_1_68_0/boost/type_traits/common_type.hpp \
		../boost_1_68_0/boost/type_traits/decay.hpp \
		../boost_1_68_0/boost/type_traits/remove_bounds.hpp \
		../boost_1_68_0/boost/type_traits/remove_extent.hpp \
		../boost_1_68_0/boost/type_traits/detail/common_type_impl.hpp \
		../boost_1_68_0/boost/type_traits/detail/common_arithmetic_type.hpp \
		../boost_1_68_0/boost/type_traits/detail/composite_pointer_type.hpp \
		../boost_1_68_0/boost/type_traits/copy_cv.hpp \
		../boost_1_68_0/boost/type_traits/is_base_of.hpp \
		../boost_1_68_0/boost/type_traits/detail/composite_member_pointer_type.hpp \
		../boost_1_68_0/boost/type_traits/remove_pointer.hpp \
		../boost_1_68_0/boost/type_traits/type_identity.hpp \
		../boost_1_68_0/boost/type_traits/detail/mp_defer.hpp \
		../boost_1_68_0/boost/type_traits/extent.hpp \
		../boost_1_68_0/boost/type_traits/floating_point_promotion.hpp \
		../boost_1_68_0/boost/type_traits/function_traits.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_and.hpp \
		../boost_1_68_0/boost/type_traits/detail/has_binary_operator.hpp \
		../boost_1_68_0/boost/type_traits/make_void.hpp \
		../boost_1_68_0/boost/type_traits/detail/is_likely_lambda.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_and_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_or.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_or_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_xor.hpp \
		../boost_1_68_0/boost/type_traits/has_bit_xor_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_complement.hpp \
		../boost_1_68_0/boost/type_traits/detail/has_prefix_operator.hpp \
		../boost_1_68_0/boost/type_traits/has_dereference.hpp \
		../boost_1_68_0/boost/type_traits/has_divides.hpp \
		../boost_1_68_0/boost/type_traits/has_divides_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_equal_to.hpp \
		../boost_1_68_0/boost/type_traits/has_greater.hpp \
		../boost_1_68_0/boost/type_traits/has_greater_equal.hpp \
		../boost_1_68_0/boost/type_traits/has_left_shift.hpp \
		../boost_1_68_0/boost/type_traits/has_left_shift_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_less.hpp \
		../boost_1_68_0/boost/type_traits/has_less_equal.hpp \
		../boost_1_68_0/boost/type_traits/has_logical_and.hpp \
		../boost_1_68_0/boost/type_traits/has_logical_not.hpp \
		../boost_1_68_0/boost/type_traits/has_logical_or.hpp \
		../boost_1_68_0/boost/type_traits/has_minus.hpp \
		../boost_1_68_0/boost/type_traits/has_minus_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_modulus.hpp \
		../boost_1_68_0/boost/type_traits/has_modulus_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_multiplies.hpp \
		../boost_1_68_0/boost/type_traits/has_multiplies_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_negate.hpp \
		../boost_1_68_0/boost/type_traits/has_new_operator.hpp \
		../boost_1_68_0/boost/type_traits/has_not_equal_to.hpp \
		../boost_1_68_0/boost/type_traits/has_nothrow_destructor.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_destructor.hpp \
		../boost_1_68_0/boost/type_traits/has_plus.hpp \
		../boost_1_68_0/boost/type_traits/has_plus_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_post_decrement.hpp \
		../boost_1_68_0/boost/type_traits/detail/has_postfix_operator.hpp \
		../boost_1_68_0/boost/type_traits/has_post_increment.hpp \
		../boost_1_68_0/boost/type_traits/has_pre_decrement.hpp \
		../boost_1_68_0/boost/type_traits/has_pre_increment.hpp \
		../boost_1_68_0/boost/type_traits/has_right_shift.hpp \
		../boost_1_68_0/boost/type_traits/has_right_shift_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_move_assign.hpp \
		../boost_1_68_0/boost/type_traits/has_trivial_move_constructor.hpp \
		../boost_1_68_0/boost/type_traits/has_unary_minus.hpp \
		../boost_1_68_0/boost/type_traits/has_unary_plus.hpp \
		../boost_1_68_0/boost/type_traits/has_virtual_destructor.hpp \
		../boost_1_68_0/boost/type_traits/is_complex.hpp \
		../boost_1_68_0/boost/type_traits/is_compound.hpp \
		../boost_1_68_0/boost/type_traits/is_copy_assignable.hpp \
		../boost_1_68_0/boost/type_traits/is_empty.hpp \
		../boost_1_68_0/boost/type_traits/is_final.hpp \
		../boost_1_68_0/boost/type_traits/is_float.hpp \
		../boost_1_68_0/boost/type_traits/is_list_constructible.hpp \
		../boost_1_68_0/boost/type_traits/is_member_object_pointer.hpp \
		../boost_1_68_0/boost/type_traits/is_nothrow_move_assignable.hpp \
		../boost_1_68_0/boost/type_traits/is_nothrow_move_constructible.hpp \
		../boost_1_68_0/boost/type_traits/is_nothrow_swappable.hpp \
		../boost_1_68_0/boost/type_traits/is_object.hpp \
		../boost_1_68_0/boost/type_traits/is_signed.hpp \
		../boost_1_68_0/boost/type_traits/is_stateless.hpp \
		../boost_1_68_0/boost/type_traits/is_unsigned.hpp \
		../boost_1_68_0/boost/type_traits/is_virtual_base_of.hpp \
		../boost_1_68_0/boost/type_traits/make_signed.hpp \
		../boost_1_68_0/boost/type_traits/make_unsigned.hpp \
		../boost_1_68_0/boost/type_traits/rank.hpp \
		../boost_1_68_0/boost/type_traits/remove_cv_ref.hpp \
		../boost_1_68_0/boost/type_traits/remove_volatile.hpp \
		../boost_1_68_0/boost/type_traits/integral_promotion.hpp \
		../boost_1_68_0/boost/type_traits/promote.hpp \
		../boost_1_68_0/boost/typeof/typeof.hpp \
		../boost_1_68_0/boost/typeof/dmc/typeof_impl.hpp \
		../boost_1_68_0/boost/typeof/msvc/typeof_impl.hpp \
		../boost_1_68_0/boost/typeof/unsupported.hpp \
		../boost_1_68_0/boost/typeof/message.hpp \
		../boost_1_68_0/boost/typeof/typeof_impl.hpp \
		../boost_1_68_0/boost/mpl/size_t.hpp \
		../boost_1_68_0/boost/mpl/size_t_fwd.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum.hpp \
		../boost_1_68_0/boost/typeof/encode_decode.hpp \
		../boost_1_68_0/boost/typeof/vector.hpp \
		../boost_1_68_0/boost/preprocessor/iteration/self.hpp \
		../boost_1_68_0/boost/typeof/vector50.hpp \
		../boost_1_68_0/boost/typeof/vector100.hpp \
		../boost_1_68_0/boost/typeof/vector150.hpp \
		../boost_1_68_0/boost/typeof/vector200.hpp \
		../boost_1_68_0/boost/preprocessor/enum_params.hpp \
		../boost_1_68_0/boost/preprocessor/repeat_from_to.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/repeat_from_to.hpp \
		../boost_1_68_0/boost/preprocessor/iteration/local.hpp \
		../boost_1_68_0/boost/preprocessor/logical/not.hpp \
		../boost_1_68_0/boost/typeof/type_encoding.hpp \
		../boost_1_68_0/boost/typeof/template_encoding.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_trailing.hpp \
		../boost_1_68_0/boost/preprocessor/detail/is_unary.hpp \
		../boost_1_68_0/boost/preprocessor/seq/transform.hpp \
		../boost_1_68_0/boost/preprocessor/seq/for_each_i.hpp \
		../boost_1_68_0/boost/preprocessor/seq/cat.hpp \
		../boost_1_68_0/boost/typeof/int_encoding.hpp \
		../boost_1_68_0/boost/typeof/type_template_param.hpp \
		../boost_1_68_0/boost/typeof/integral_template_param.hpp \
		../boost_1_68_0/boost/typeof/template_template_param.hpp \
		../boost_1_68_0/boost/preprocessor/logical/or.hpp \
		../boost_1_68_0/boost/preprocessor/logical/bitor.hpp \
		../boost_1_68_0/boost/preprocessor/seq/enum.hpp \
		../boost_1_68_0/boost/typeof/modifiers.hpp \
		../boost_1_68_0/boost/typeof/pointers_data_members.hpp \
		../boost_1_68_0/boost/typeof/encode_decode_params.hpp \
		../boost_1_68_0/boost/typeof/register_functions.hpp \
		../boost_1_68_0/boost/preprocessor/if.hpp \
		../boost_1_68_0/boost/typeof/register_fundamental.hpp \
		../boost_1_68_0/boost/typeof/decltype.hpp \
		../boost_1_68_0/boost/typeof/native.hpp \
		../boost_1_68_0/boost/numeric/ublas/vector_expression.hpp \
		../boost_1_68_0/boost/numeric/ublas/expression_types.hpp \
		../boost_1_68_0/boost/numeric/ublas/functional.hpp \
		../boost_1_68_0/boost/core/ignore_unused.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/duff.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/raw.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/vector_assign.hpp \
		../boost_1_68_0/boost/numeric/ublas/matrix_expression.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/matrix_assign.hpp \
		../boost_1_68_0/boost/numeric/ublas/io.hpp \
		../boost_1_68_0/boost/numeric/ublas/lu.hpp \
		../boost_1_68_0/boost/numeric/ublas/operation.hpp \
		../boost_1_68_0/boost/numeric/ublas/matrix_proxy.hpp \
		../boost_1_68_0/boost/numeric/ublas/detail/temporary.hpp \
		../boost_1_68_0/boost/numeric/ublas/vector_proxy.hpp \
		../boost_1_68_0/boost/numeric/ublas/triangular.hpp \
		../boost_1_68_0/boost/math/special_functions/ellint_2.hpp \
		../boost_1_68_0/boost/math/special_functions/math_fwd.hpp \
		../boost_1_68_0/boost/math/special_functions/detail/round_fwd.hpp \
		../boost_1_68_0/boost/math/tools/promotion.hpp \
		../boost_1_68_0/boost/math/tools/config.hpp \
		../boost_1_68_0/boost/math/tools/user.hpp \
		../boost_1_68_0/boost/type.hpp \
		../boost_1_68_0/boost/non_type.hpp \
		../boost_1_68_0/boost/math/policies/policy.hpp \
		../boost_1_68_0/boost/mpl/list.hpp \
		../boost_1_68_0/boost/mpl/limits/list.hpp \
		../boost_1_68_0/boost/mpl/aux_/sequence_wrapper.hpp \
		../boost_1_68_0/boost/preprocessor/enum_params_with_a_default.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_params_with_a_default.hpp \
		../boost_1_68_0/boost/preprocessor/facilities/intercept.hpp \
		../boost_1_68_0/boost/preprocessor/repetition/enum_binary_params.hpp \
		../boost_1_68_0/boost/preprocessor/enum.hpp \
		../boost_1_68_0/boost/mpl/contains.hpp \
		../boost_1_68_0/boost/mpl/contains_fwd.hpp \
		../boost_1_68_0/boost/mpl/aux_/contains_impl.hpp \
		../boost_1_68_0/boost/mpl/find.hpp \
		../boost_1_68_0/boost/mpl/find_if.hpp \
		../boost_1_68_0/boost/mpl/aux_/find_if_pred.hpp \
		../boost_1_68_0/boost/mpl/aux_/iter_apply.hpp \
		../boost_1_68_0/boost/mpl/iter_fold_if.hpp \
		../boost_1_68_0/boost/mpl/logical.hpp \
		../boost_1_68_0/boost/mpl/pair.hpp \
		../boost_1_68_0/boost/mpl/aux_/iter_fold_if_impl.hpp \
		../boost_1_68_0/boost/mpl/same_as.hpp \
		../boost_1_68_0/boost/mpl/aux_/lambda_spec.hpp \
		../boost_1_68_0/boost/mpl/remove_if.hpp \
		../boost_1_68_0/boost/mpl/fold.hpp \
		../boost_1_68_0/boost/mpl/O1_size.hpp \
		../boost_1_68_0/boost/mpl/aux_/O1_size_impl.hpp \
		../boost_1_68_0/boost/mpl/aux_/has_size.hpp \
		../boost_1_68_0/boost/mpl/aux_/fold_impl.hpp \
		../boost_1_68_0/boost/mpl/aux_/fold_impl_body.hpp \
		../boost_1_68_0/boost/mpl/reverse_fold.hpp \
		../boost_1_68_0/boost/mpl/aux_/reverse_fold_impl.hpp \
		../boost_1_68_0/boost/mpl/aux_/reverse_fold_impl_body.hpp \
		../boost_1_68_0/boost/mpl/aux_/inserter_algorithm.hpp \
		../boost_1_68_0/boost/mpl/back_inserter.hpp \
		../boost_1_68_0/boost/mpl/push_back.hpp \
		../boost_1_68_0/boost/mpl/aux_/push_back_impl.hpp \
		../boost_1_68_0/boost/mpl/inserter.hpp \
		../boost_1_68_0/boost/mpl/front_inserter.hpp \
		../boost_1_68_0/boost/mpl/push_front.hpp \
		../boost_1_68_0/boost/mpl/aux_/push_front_impl.hpp \
		../boost_1_68_0/boost/mpl/clear.hpp \
		../boost_1_68_0/boost/mpl/aux_/clear_impl.hpp \
		../boost_1_68_0/boost/mpl/vector.hpp \
		../boost_1_68_0/boost/mpl/limits/vector.hpp \
		../boost_1_68_0/boost/mpl/size.hpp \
		../boost_1_68_0/boost/mpl/aux_/size_impl.hpp \
		../boost_1_68_0/boost/mpl/distance.hpp \
		../boost_1_68_0/boost/mpl/iter_fold.hpp \
		../boost_1_68_0/boost/mpl/aux_/iter_fold_impl.hpp \
		../boost_1_68_0/boost/mpl/iterator_range.hpp \
		../boost_1_68_0/boost/mpl/comparison.hpp \
		../boost_1_68_0/boost/mpl/not_equal_to.hpp \
		../boost_1_68_0/boost/mpl/less_equal.hpp \
		../boost_1_68_0/boost/mpl/greater_equal.hpp \
		../boost_1_68_0/boost/config/no_tr1/complex.hpp \
		../boost_1_68_0/boost/math/special_functions/ellint_rf.hpp \
		../boost_1_68_0/boost/math/constants/constants.hpp \
		../boost_1_68_0/boost/math/tools/precision.hpp \
		../boost_1_68_0/boost/math/tools/convert_from_string.hpp \
		../boost_1_68_0/boost/lexical_cast.hpp \
		../boost_1_68_0/boost/range/iterator_range_core.hpp \
		../boost_1_68_0/boost/iterator/iterator_traits.hpp \
		../boost_1_68_0/boost/iterator/iterator_facade.hpp \
		../boost_1_68_0/boost/iterator/interoperable.hpp \
		../boost_1_68_0/boost/iterator/detail/config_def.hpp \
		../boost_1_68_0/boost/iterator/detail/config_undef.hpp \
		../boost_1_68_0/boost/iterator/iterator_categories.hpp \
		../boost_1_68_0/boost/iterator/detail/facade_iterator_category.hpp \
		../boost_1_68_0/boost/detail/indirect_traits.hpp \
		../boost_1_68_0/boost/iterator/detail/enable_if.hpp \
		../boost_1_68_0/boost/utility/addressof.hpp \
		../boost_1_68_0/boost/range/functions.hpp \
		../boost_1_68_0/boost/range/begin.hpp \
		../boost_1_68_0/boost/range/config.hpp \
		../boost_1_68_0/boost/range/detail/begin.hpp \
		../boost_1_68_0/boost/range/iterator.hpp \
		../boost_1_68_0/boost/range/range_fwd.hpp \
		../boost_1_68_0/boost/range/mutable_iterator.hpp \
		../boost_1_68_0/boost/range/detail/extract_optional_type.hpp \
		../boost_1_68_0/boost/range/detail/msvc_has_iterator_workaround.hpp \
		../boost_1_68_0/boost/range/const_iterator.hpp \
		../boost_1_68_0/boost/range/detail/common.hpp \
		../boost_1_68_0/boost/range/detail/sfinae.hpp \
		../boost_1_68_0/boost/range/end.hpp \
		../boost_1_68_0/boost/range/detail/end.hpp \
		../boost_1_68_0/boost/range/detail/implementation_help.hpp \
		../boost_1_68_0/boost/range/size.hpp \
		../boost_1_68_0/boost/range/size_type.hpp \
		../boost_1_68_0/boost/range/difference_type.hpp \
		../boost_1_68_0/boost/range/has_range_iterator.hpp \
		../boost_1_68_0/boost/range/concepts.hpp \
		../boost_1_68_0/boost/concept_check.hpp \
		../boost_1_68_0/boost/concept/assert.hpp \
		../boost_1_68_0/boost/concept/detail/msvc.hpp \
		../boost_1_68_0/boost/concept/detail/backward_compatibility.hpp \
		../boost_1_68_0/boost/concept/detail/has_constraints.hpp \
		../boost_1_68_0/boost/concept/detail/borland.hpp \
		../boost_1_68_0/boost/concept/detail/general.hpp \
		../boost_1_68_0/boost/type_traits/conversion_traits.hpp \
		../boost_1_68_0/boost/concept/usage.hpp \
		../boost_1_68_0/boost/concept/detail/concept_def.hpp \
		../boost_1_68_0/boost/concept/detail/concept_undef.hpp \
		../boost_1_68_0/boost/iterator/iterator_concepts.hpp \
		../boost_1_68_0/boost/range/value_type.hpp \
		../boost_1_68_0/boost/range/detail/misc_concept.hpp \
		../boost_1_68_0/boost/range/detail/has_member_size.hpp \
		../boost_1_68_0/boost/utility.hpp \
		../boost_1_68_0/boost/utility/base_from_member.hpp \
		../boost_1_68_0/boost/utility/binary.hpp \
		../boost_1_68_0/boost/preprocessor/control/deduce_d.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/mod.hpp \
		../boost_1_68_0/boost/preprocessor/arithmetic/detail/div_base.hpp \
		../boost_1_68_0/boost/preprocessor/comparison/less_equal.hpp \
		../boost_1_68_0/boost/utility/identity_type.hpp \
		../boost_1_68_0/boost/range/distance.hpp \
		../boost_1_68_0/boost/iterator/distance.hpp \
		../boost_1_68_0/boost/range/empty.hpp \
		../boost_1_68_0/boost/range/rbegin.hpp \
		../boost_1_68_0/boost/range/reverse_iterator.hpp \
		../boost_1_68_0/boost/iterator/reverse_iterator.hpp \
		../boost_1_68_0/boost/iterator/iterator_adaptor.hpp \
		../boost_1_68_0/boost/range/rend.hpp \
		../boost_1_68_0/boost/range/algorithm/equal.hpp \
		../boost_1_68_0/boost/range/detail/safe_bool.hpp \
		../boost_1_68_0/boost/next_prior.hpp \
		../boost_1_68_0/boost/iterator/advance.hpp \
		../boost_1_68_0/boost/lexical_cast/bad_lexical_cast.hpp \
		../boost_1_68_0/boost/lexical_cast/try_lexical_convert.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/is_character.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/converter_numeric.hpp \
		../boost_1_68_0/boost/numeric/conversion/cast.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/old_numeric_cast.hpp \
		../boost_1_68_0/boost/numeric/conversion/converter_policies.hpp \
		../boost_1_68_0/boost/numeric/conversion/converter.hpp \
		../boost_1_68_0/boost/numeric/conversion/conversion_traits.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/conversion_traits.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/meta.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/int_float_mixture.hpp \
		../boost_1_68_0/boost/numeric/conversion/int_float_mixture_enum.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/sign_mixture.hpp \
		../boost_1_68_0/boost/numeric/conversion/sign_mixture_enum.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/udt_builtin_mixture.hpp \
		../boost_1_68_0/boost/numeric/conversion/udt_builtin_mixture_enum.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/is_subranged.hpp \
		../boost_1_68_0/boost/mpl/multiplies.hpp \
		../boost_1_68_0/boost/mpl/times.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/converter.hpp \
		../boost_1_68_0/boost/numeric/conversion/bounds.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/bounds.hpp \
		../boost_1_68_0/boost/numeric/conversion/numeric_cast_traits.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/numeric_cast_traits.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_common.hpp \
		../boost_1_68_0/boost/numeric/conversion/detail/preprocessed/numeric_cast_traits_long_long.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/converter_lexical.hpp \
		../boost_1_68_0/boost/detail/lcast_precision.hpp \
		../boost_1_68_0/boost/integer_traits.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/widest_char.hpp \
		../boost_1_68_0/boost/array.hpp \
		../boost_1_68_0/boost/swap.hpp \
		../boost_1_68_0/boost/core/swap.hpp \
		../boost_1_68_0/boost/detail/iterator.hpp \
		../boost_1_68_0/boost/container/container_fwd.hpp \
		../boost_1_68_0/boost/container/detail/std_fwd.hpp \
		../boost_1_68_0/boost/move/detail/std_ns_begin.hpp \
		../boost_1_68_0/boost/move/detail/std_ns_end.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/converter_lexical_streams.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/lcast_char_constants.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/lcast_unsigned_converters.hpp \
		../boost_1_68_0/boost/lexical_cast/detail/inf_nan.hpp \
		../boost_1_68_0/boost/math/special_functions/sign.hpp \
		../boost_1_68_0/boost/math/special_functions/detail/fp_traits.hpp \
		../boost_1_68_0/boost/detail/endian.hpp \
		../boost_1_68_0/boost/predef/detail/endian_compat.h \
		../boost_1_68_0/boost/math/special_functions/fpclassify.hpp \
		../boost_1_68_0/boost/math/tools/real_cast.hpp \
		../boost_1_68_0/boost/integer.hpp \
		../boost_1_68_0/boost/integer_fwd.hpp \
		../boost_1_68_0/boost/detail/basic_pointerbuf.hpp \
		../boost_1_68_0/boost/utility/declval.hpp \
		../boost_1_68_0/boost/math/constants/calculate_constants.hpp \
		../boost_1_68_0/boost/math/special_functions/trunc.hpp \
		../boost_1_68_0/boost/math/policies/error_handling.hpp \
		../boost_1_68_0/boost/math/special_functions/ellint_rc.hpp \
		../boost_1_68_0/boost/math/special_functions/log1p.hpp \
		../boost_1_68_0/boost/math/tools/series.hpp \
		../boost_1_68_0/boost/math/tools/rational.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner1_20.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner2_20.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/polynomial_horner3_20.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner1_20.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner2_20.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_2.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_3.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_4.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_5.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_6.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_7.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_8.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_9.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_10.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_11.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_12.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_13.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_14.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_15.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_16.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_17.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_18.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_19.hpp \
		../boost_1_68_0/boost/math/tools/detail/rational_horner3_20.hpp \
		../boost_1_68_0/boost/math/tools/big_constant.hpp \
		../boost_1_68_0/boost/math/special_functions/ellint_rd.hpp \
		../boost_1_68_0/boost/math/special_functions/pow.hpp \
		../boost_1_68_0/boost/math/special_functions/ellint_rg.hpp \
		../boost_1_68_0/boost/math/tools/workaround.hpp \
		../boost_1_68_0/boost/math/special_functions/round.hpp \
		../muparser-2.2.5/include/muParser.h \
		../muparser-2.2.5/include/muParserBase.h \
		../muparser-2.2.5/include/muParserDef.h \
		../muparser-2.2.5/include/muParserFixes.h \
		../muparser-2.2.5/include/muParserStack.h \
		../muparser-2.2.5/include/muParserError.h \
		../muparser-2.2.5/include/muParserToken.h \
		../muparser-2.2.5/include/muParserCallback.h \
		../muparser-2.2.5/include/muParserTokenReader.h \
		../muparser-2.2.5/include/muParserBytecode.h \
		../muparser-2.2.5/include/muParserTemplateMagic.h \
		lib/math/rs_math.h \
		Header/rs_vector.h \
		Header/rs.h \
		Header/rs_debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rs_math.o lib/math/rs_math.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

